"""Corrigindo restricao de tamanho para 120

Revision ID: 303bf7dc75eb
Revises: ed28223cae01
Create Date: 2026-08-05 22:25:33.601355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303bf7dc75eb'
down_revision: Union[str, Sequence[str], None] = 'ed28223cae01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Acidentes_Registrados', 'condicao_metereologica',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'tipo_pista',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'tracado_via',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Acidentes_Registrados', 'tracado_via',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'tipo_pista',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'condicao_metereologica',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
