"""Corrigindo restricao de tamanho

Revision ID: ed28223cae01
Revises: 520ac9e3812e
Create Date: 2026-08-05 21:50:49.274963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed28223cae01'
down_revision: Union[str, Sequence[str], None] = '520ac9e3812e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Acidentes_Registrados', 'tipo_acidente',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'condicao_metereologica',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'tipo_pista',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'tracado_via',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Acidentes_Registrados', 'tracado_via',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'tipo_pista',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'condicao_metereologica',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('Acidentes_Registrados', 'tipo_acidente',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###
